again

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -123,12 +123,26 @@ jobs:
 
           # New server is up and running - prepare the old one for death
           # retrieve current deployment priv key
-          cat <<EOF >~/.ssh/id_rsa_old
-          echo ${{ secrets.HETZNER_SSH_PRIVKEY }}
-          EOF
+          echo ${{ secrets.HETZNER_SSH_PRIVKEY }} | base64 -d | tee ~/.ssh/id_rsa_old
           chmod 400 ~/.ssh/id_rsa_old
 
           export SLACK_NOTIFY_TOKEN=$(echo ${{ secrets.ORG_SLACK_NOTIFICATIONS_TOKEN }} | base64 -d)
+          # update Vault CIDRs with new addresses
+          #curl -s -X POST -d token=$SLACK_NOTIFY_TOKEN -d channel=C33QYV3PW \
+          #  -d text="vfa update $NEW_SERVER_IPV6,$NEW_SERVER_IPV4" https://slack.com/api/chat.postMessage
+
+          # Use existing server to update new firewall rules for home network & vault instance
+          envsubst '${MASTER_HOST} ${SLAVE_HOST} ${BUILD_HOST} ${NEW_SERVER_IPV6} ${OLD_SERVER_IPV6}' < scripts/firewall_rules.sh > fw_rules.sh
+          # if scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa_old fw_rules.sh root@ackerson.de:~/ ; then
+          #   if ! ssh -i ~/.ssh/id_rsa_old root@ackerson.de /bin/bash /root/fw_rules.sh ; then
+          #     curl -s -o /dev/null -X POST -d token=$SLACK_NOTIFY_TOKEN -d channel=C092UE0H4 \
+          #       -d text="Failed to update firewall rules: ${OLD_SERVER_IPV6} => ${NEW_SERVER_IPV6}" \
+          #       https://slack.com/api/chat.postMessage
+          #   fi
+          # else
+          #   curl -s -o /dev/null -X POST -d token=$SLACK_NOTIFY_TOKEN -d channel=C092UE0H4 \
+          #     -d text="Unable to reach ackerson.de => Perhaps this is first run?" https://slack.com/api/chat.postMessage
+          # fi
 
           # update PRIVKEY to new one for subsequent deployments
           # grab github.py from pi-ops repo
@@ -140,7 +154,7 @@ jobs:
           export GITHUB_SECRETS_PK_PEM=$(echo ${{ secrets.ORG_GITHUB_SECRETS_PK_PEM }} | base64 -d)
           python -m pip install --upgrade pip
           pip install -r scripts/requirements.txt
-          python scripts/update_github_secret.py --name HETZNER_SSH_PRIVKEY -b true -f ~/.ssh/id_rsa
+          python scripts/update_github_secret.py --name HETZNER_SSH_PRIVKEY --storeB64 -f ~/.ssh/id_rsa
 
           # perform final cleanup
           # ./hetzner -fn=cleanupDeploy -serverID=$NEW_SERVER_ID -tag=homepage # if serverID provided, update DNS too!
@@ -152,7 +166,7 @@ jobs:
           curl -Ss -X POST -u "$GITHUB_USERNAME:$GITHUB_TOKEN" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/ackersonde/ackerson.de-go/actions/workflows/build.yml/dispatches \
-            -d '{"ref":"hetzner", "ca_pub_fingerprint":"TADA"}'
+            -d '{"ref":"hetzner","inputs":{"ca_pub_fingerprint":"$NEW_SERVER_ID"}}'
           # curl -Ss -X POST -u "$GITHUB_USERNAME:$GITHUB_TOKEN" \
           #   -H "Accept: application/vnd.github.v3+json" \
           #   https://api.github.com/repos/ackersonde/bender-slackbot/actions/workflows/build.yml/dispatches \
